spring:
  config:
    import: optional:file:.env[.properties]
  profiles:
    active: local

  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS}

  datasource:
    url: jdbc:mariadb://${DB_HOST}:${DB_PORT:3306}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      connection-timezone: Asia/Seoul

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MariaDBDialect

        jdbc:
          batch_size: 1000
          time_zone: Asia/Seoul
        order_inserts: true
        order_updates: true
        generate_statistics: false
    show-sql: true

  jackson:
    time-zone: Asia/Seoul
  mvc:
    time-zone: Asia/Seoul

  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

  file:
    upload-dir: ${SFTP_REMOTE_DIR}

app:
  jwt:
    secret: ${JWT_SECRET_BASE64}
    issuer: yobuddy
    access-expiration-ms: ${JWT_ACCESS_EXPIRATION_MS:900000}
    refresh-expiration-ms: ${JWT_REFRESH_EXPIRATION_MS:1209600000}

sftp:
  host: ${SFTP_HOST}
  port: ${SFTP_PORT}
  user: ${SFTP_USER}
  password: ${SFTP_PASSWORD}
