name: Backend CI/CD

on:
  push:
    branches: ["main"]

jobs:
  deploy-idle:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Determine Idle Environment
        run: |
          echo "IDLE=${{ secrets.IDLE_ENV }}"
          if [ "${{ secrets.IDLE_ENV }}" = "blue" ]; then
            echo "DEPLOY_ENV=blue" >> $GITHUB_ENV
          else
            echo "DEPLOY_ENV=green" >> $GITHUB_ENV
          fi

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build JAR
        run: ./gradlew clean build -x test

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build & Push Docker image to IDLE env
        run: |
          REPO=${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/yobuddy-back-repo
          docker build -t yobuddy-backend .
          docker tag yobuddy-backend:latest $REPO:${{ env.DEPLOY_ENV }}
          docker push $REPO:${{ env.DEPLOY_ENV }}

      - name: Refresh Idle ASG
        run: |
          if [ "${{ env.DEPLOY_ENV }}" = "blue" ]; then
            ASG="${{ secrets.ASG_BLUE_NAME }}"
          else
            ASG="${{ secrets.ASG_GREEN_NAME }}"
          fi

          aws autoscaling start-instance-refresh \
            --auto-scaling-group-name $ASG \
            --preferences '{"MinHealthyPercentage": 100, "InstanceWarmup": 60}'
